name: food_delivery
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
 flutter:
  sdk: flutter


cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  curved_navigation_bar: ^0.3.7

flutter:


  uses-material-design: true

  assets:
    - assets/images/welcome.png
    - assets/images/signin.png
    - assets/images/bugger.png
    - assets/images/pizza.jpg
    - assets/images/breakfast.jpg
    - assets/images/chicken.jpg
    - assets/images/rice.jpg
    - assets/images/salad.jpg


 
